FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04

# Prevent stop building ubuntu at time zone selection.
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC && \
    sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    apt update

# Prepare and empty machine for building
RUN apt-get install -y \
    git \
    cmake \
    build-essential \
    wget \
    zip \
    libboost-filesystem-dev

# Build and install ceres solver
RUN apt-get -y install \
    libgoogle-glog-dev \
    libgflags-dev \
    libatlas-base-dev \
    libeigen3-dev \
    libsuitesparse-dev



ENV CUDA_HOME=$CUDA_HOME:/usr/local/cuda
ENV PATH=$PATH:/usr/lib:/usr/local/cuda/bin


ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/face_search/libs/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/face_search/libs/sdk/lib/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/face_search/libs/thirdparty/onnxruntime/lib/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/face_search/libs/thirdparty/opencv4-ffmpeg/lib/


# 安装OpenSSH服务
RUN apt-get update && apt-get install -y openssh-server

# 设置SSH无密码登录（非生产建议）
RUN mkdir /var/run/sshd
RUN echo 'root:123456' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# 确保SSH服务在容器启动时自动运行
CMD ["/usr/sbin/sshd", "-D"]


ADD . /root/face_search

WORKDIR /root/face_search

RUN apt-get install -y wget software-properties-common gcc

#golang环境
RUN wget https://dl.google.com/go/go1.20.1.linux-amd64.tar.gz --no-check-certificate
RUN tar -xf go1.20.1.linux-amd64.tar.gz -C /usr/local/
ENV PATH=$PATH:/usr/local/go/bin
RUN go env -w GOBIN=/usr/local/go/bin
RUN go env -w GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE=on
ENV GOPATH=/root/go
ENV GOROOT=/usr/local/go
RUN rm -f go1.20.1.linux-amd64.tar.gz

ENV GODEBUG=cgocheck=0
ENV CGO_ENABLED=1

WORKDIR /go/cache
RUN go env -w GOPROXY=https://goproxy.cn,direct && \
    go env -w GOPRIVATE=git.hiscene.net && \
    git config --global url."git@git.hiscene.net:".insteadOf "https://git.hiscene.net/"

RUN mkdir -p /root/.ssh && chmod 0700 /root/.ssh
ADD id_rsa /root/.ssh/id_rsa
ADD id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 600 /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa.pub && \
    ssh-keyscan -t rsa git.hiscene.net >> /root/.ssh/known_hosts

#git仓库打tag
RUN go env -w GOPROXY=https://goproxy.cn,direct


COPY go.mod go.sum ./
RUN go mod download

# 暴露22端口
EXPOSE 22
EXPOSE 6002

# docker build -t face_jq_dev .
# docker run -d --runtime=nvidia --gpus all -p 22:22 -p 6002:6002 --privileged=true --mac_address=02:42:ac:12:00:02 --name face_jq_dev face_jq_dev
