name: "ar_tank"
version: "v1.0"

server:
  env: "dev"
  http:
    addr: 0.0.0.0:6002
    timeout: 60s

logger:
  path: ./logs

discovery:
  ipAddr: 192.168.18.66
  port: 8848
  timeout: 5
  onOff: true

microServices:
  baseService:
    name:  "base-service.grpc"
    timeout:  60
    endpoint:  "localhost:9001"
    isLocal:  true

registeTimer: 0 #定时注册，单位分钟，0=不启用
startUnRegiste: false #启动时注销以前的人脸
match: 0.85
matchTimeRange: 0 #只保留与算法匹配度最高的照片拍摄时间不超过matchTimeRange分钟， 0=不限制时间
