all: search registe unregiste

search:
	GOOS=windows GOARCH=amd64 go build -o FaceSearch.exe face_search.go

registe:
	GOOS=windows GOARCH=amd64 go build -o FaceRegiste.exe face_registe.go

unregiste:
	GOOS=windows GOARCH=amd64 go build -o FaceUnRegiste.exe unregiste_all.go
