// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v5.26.1
// source: biz/v1/face_recognize.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFaceRecognizeRegisteByPath = "/api.biz.v1.FaceRecognize/RegisteByPath"
const OperationFaceRecognizeUnRegisteAll = "/api.biz.v1.FaceRecognize/UnRegisteAll"

type FaceRecognizeHTTPServer interface {
	// RegisteByPath人脸注册-从默认目录读取注册图
	RegisteByPath(context.Context, *EmptyRequest) (*EmptyReply, error)
	// UnRegisteAll人脸注销-所有人脸
	UnRegisteAll(context.Context, *EmptyRequest) (*EmptyReply, error)
}

func RegisterFaceRecognizeHTTPServer(s *http.Server, srv FaceRecognizeHTTPServer) {
	r := s.Route("/")
	r.POST("/face/registe/path", _FaceRecognize_RegisteByPath0_HTTP_Handler(srv))
	r.POST("/face/unregiste/all", _FaceRecognize_UnRegisteAll0_HTTP_Handler(srv))
}

func _FaceRecognize_RegisteByPath0_HTTP_Handler(srv FaceRecognizeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EmptyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFaceRecognizeRegisteByPath)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisteByPath(ctx, req.(*EmptyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _FaceRecognize_UnRegisteAll0_HTTP_Handler(srv FaceRecognizeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EmptyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFaceRecognizeUnRegisteAll)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnRegisteAll(ctx, req.(*EmptyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

type FaceRecognizeHTTPClient interface {
	RegisteByPath(ctx context.Context, req *EmptyRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
	UnRegisteAll(ctx context.Context, req *EmptyRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
}

type FaceRecognizeHTTPClientImpl struct {
	cc *http.Client
}

func NewFaceRecognizeHTTPClient(client *http.Client) FaceRecognizeHTTPClient {
	return &FaceRecognizeHTTPClientImpl{client}
}

func (c *FaceRecognizeHTTPClientImpl) RegisteByPath(ctx context.Context, in *EmptyRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/face/registe/path"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFaceRecognizeRegisteByPath))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FaceRecognizeHTTPClientImpl) UnRegisteAll(ctx context.Context, in *EmptyRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/face/unregiste/all"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFaceRecognizeUnRegisteAll))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
