// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.26.1
// source: biz/v1/face_recognize.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_v1_face_recognize_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_face_recognize_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_biz_v1_face_recognize_proto_rawDescGZIP(), []int{0}
}

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_v1_face_recognize_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_face_recognize_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_biz_v1_face_recognize_proto_rawDescGZIP(), []int{1}
}

type RegisteStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registering bool `protobuf:"varint,1,opt,name=registering,proto3" json:"registering,omitempty"`
}

func (x *RegisteStatusReply) Reset() {
	*x = RegisteStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_v1_face_recognize_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteStatusReply) ProtoMessage() {}

func (x *RegisteStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_face_recognize_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteStatusReply.ProtoReflect.Descriptor instead.
func (*RegisteStatusReply) Descriptor() ([]byte, []int) {
	return file_biz_v1_face_recognize_proto_rawDescGZIP(), []int{2}
}

func (x *RegisteStatusReply) GetRegistering() bool {
	if x != nil {
		return x.Registering
	}
	return false
}

type RegisteByPathReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistedSuccNum   int32 `protobuf:"varint,1,opt,name=registedSuccNum,proto3" json:"registedSuccNum,omitempty"`
	RegistedFailedNum int32 `protobuf:"varint,2,opt,name=registedFailedNum,proto3" json:"registedFailedNum,omitempty"`
	NewFaceNum        int32 `protobuf:"varint,3,opt,name=newFaceNum,proto3" json:"newFaceNum,omitempty"`
}

func (x *RegisteByPathReply) Reset() {
	*x = RegisteByPathReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_v1_face_recognize_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteByPathReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteByPathReply) ProtoMessage() {}

func (x *RegisteByPathReply) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_face_recognize_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteByPathReply.ProtoReflect.Descriptor instead.
func (*RegisteByPathReply) Descriptor() ([]byte, []int) {
	return file_biz_v1_face_recognize_proto_rawDescGZIP(), []int{3}
}

func (x *RegisteByPathReply) GetRegistedSuccNum() int32 {
	if x != nil {
		return x.RegistedSuccNum
	}
	return 0
}

func (x *RegisteByPathReply) GetRegistedFailedNum() int32 {
	if x != nil {
		return x.RegistedFailedNum
	}
	return 0
}

func (x *RegisteByPathReply) GetNewFaceNum() int32 {
	if x != nil {
		return x.NewFaceNum
	}
	return 0
}

type ImageType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JPG int32 `protobuf:"varint,1,opt,name=JPG,proto3" json:"JPG,omitempty"`
	PNG int32 `protobuf:"varint,2,opt,name=PNG,proto3" json:"PNG,omitempty"`
}

func (x *ImageType) Reset() {
	*x = ImageType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_v1_face_recognize_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageType) ProtoMessage() {}

func (x *ImageType) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_face_recognize_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageType.ProtoReflect.Descriptor instead.
func (*ImageType) Descriptor() ([]byte, []int) {
	return file_biz_v1_face_recognize_proto_rawDescGZIP(), []int{4}
}

func (x *ImageType) GetJPG() int32 {
	if x != nil {
		return x.JPG
	}
	return 0
}

func (x *ImageType) GetPNG() int32 {
	if x != nil {
		return x.PNG
	}
	return 0
}

type Struct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageType *ImageType `protobuf:"bytes,1,opt,name=imageType,proto3" json:"imageType,omitempty"`
	Data      []byte     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Size      []byte     `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Width     int32      `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height    int32      `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Struct) Reset() {
	*x = Struct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_v1_face_recognize_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_face_recognize_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_biz_v1_face_recognize_proto_rawDescGZIP(), []int{5}
}

func (x *Struct) GetImageType() *ImageType {
	if x != nil {
		return x.ImageType
	}
	return nil
}

func (x *Struct) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Struct) GetSize() []byte {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Struct) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Struct) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type SearchResultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*SearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SearchResultReply) Reset() {
	*x = SearchResultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_v1_face_recognize_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultReply) ProtoMessage() {}

func (x *SearchResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_face_recognize_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultReply.ProtoReflect.Descriptor instead.
func (*SearchResultReply) Descriptor() ([]byte, []int) {
	return file_biz_v1_face_recognize_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResultReply) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string  `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Match    float32 `protobuf:"fixed32,2,opt,name=match,proto3" json:"match,omitempty"`
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_v1_face_recognize_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_face_recognize_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_biz_v1_face_recognize_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResult) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SearchResult) GetMatch() float32 {
	if x != nil {
		return x.Match
	}
	return 0
}

var File_biz_v1_face_recognize_proto protoreflect.FileDescriptor

var file_biz_v1_face_recognize_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x62, 0x69, 0x7a, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x72, 0x65,
	0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61,
	0x70, 0x69, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x36, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28,
	0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x64, 0x53, 0x75, 0x63, 0x63, 0x4e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x64, 0x53, 0x75, 0x63, 0x63, 0x4e, 0x75, 0x6d, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x64, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x11, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x64, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x46, 0x61, 0x63,
	0x65, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x46,
	0x61, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x2f, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x50, 0x47, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x4a, 0x50, 0x47, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x4e, 0x47, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x50, 0x4e, 0x47, 0x22, 0x93, 0x01, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x12, 0x33, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x7a, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x47, 0x0a,
	0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x40, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x32, 0xc4, 0x02, 0x0a, 0x0d, 0x46, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x12, 0x68, 0x0a, 0x0d, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x7a, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12, 0x2f,
	0x66, 0x61, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x2f, 0x70, 0x61, 0x74,
	0x68, 0x3a, 0x01, 0x2a, 0x12, 0x67, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x7a, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x60, 0x0a,
	0x0c, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x12, 0x18, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69,
	0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x13, 0x2f, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x75,
	0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x2f, 0x61, 0x6c, 0x6c, 0x3a, 0x01, 0x2a, 0x42,
	0x0f, 0x5a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_biz_v1_face_recognize_proto_rawDescOnce sync.Once
	file_biz_v1_face_recognize_proto_rawDescData = file_biz_v1_face_recognize_proto_rawDesc
)

func file_biz_v1_face_recognize_proto_rawDescGZIP() []byte {
	file_biz_v1_face_recognize_proto_rawDescOnce.Do(func() {
		file_biz_v1_face_recognize_proto_rawDescData = protoimpl.X.CompressGZIP(file_biz_v1_face_recognize_proto_rawDescData)
	})
	return file_biz_v1_face_recognize_proto_rawDescData
}

var file_biz_v1_face_recognize_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_biz_v1_face_recognize_proto_goTypes = []interface{}{
	(*EmptyReply)(nil),         // 0: api.biz.v1.EmptyReply
	(*EmptyRequest)(nil),       // 1: api.biz.v1.EmptyRequest
	(*RegisteStatusReply)(nil), // 2: api.biz.v1.RegisteStatusReply
	(*RegisteByPathReply)(nil), // 3: api.biz.v1.RegisteByPathReply
	(*ImageType)(nil),          // 4: api.biz.v1.ImageType
	(*Struct)(nil),             // 5: api.biz.v1.struct
	(*SearchResultReply)(nil),  // 6: api.biz.v1.SearchResultReply
	(*SearchResult)(nil),       // 7: api.biz.v1.SearchResult
}
var file_biz_v1_face_recognize_proto_depIdxs = []int32{
	4, // 0: api.biz.v1.struct.imageType:type_name -> api.biz.v1.ImageType
	7, // 1: api.biz.v1.SearchResultReply.results:type_name -> api.biz.v1.SearchResult
	1, // 2: api.biz.v1.FaceRecognize.RegisteByPath:input_type -> api.biz.v1.EmptyRequest
	1, // 3: api.biz.v1.FaceRecognize.RegisteStatus:input_type -> api.biz.v1.EmptyRequest
	1, // 4: api.biz.v1.FaceRecognize.UnRegisteAll:input_type -> api.biz.v1.EmptyRequest
	3, // 5: api.biz.v1.FaceRecognize.RegisteByPath:output_type -> api.biz.v1.RegisteByPathReply
	2, // 6: api.biz.v1.FaceRecognize.RegisteStatus:output_type -> api.biz.v1.RegisteStatusReply
	0, // 7: api.biz.v1.FaceRecognize.UnRegisteAll:output_type -> api.biz.v1.EmptyReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_biz_v1_face_recognize_proto_init() }
func file_biz_v1_face_recognize_proto_init() {
	if File_biz_v1_face_recognize_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biz_v1_face_recognize_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_v1_face_recognize_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_v1_face_recognize_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_v1_face_recognize_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteByPathReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_v1_face_recognize_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_v1_face_recognize_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Struct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_v1_face_recognize_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_v1_face_recognize_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biz_v1_face_recognize_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_biz_v1_face_recognize_proto_goTypes,
		DependencyIndexes: file_biz_v1_face_recognize_proto_depIdxs,
		MessageInfos:      file_biz_v1_face_recognize_proto_msgTypes,
	}.Build()
	File_biz_v1_face_recognize_proto = out.File
	file_biz_v1_face_recognize_proto_rawDesc = nil
	file_biz_v1_face_recognize_proto_goTypes = nil
	file_biz_v1_face_recognize_proto_depIdxs = nil
}
